### PR TITLE
Broman ssl certs

### PR DESCRIPTION
**Pull request by yonglid**

### CODE REVIEW

**Comment by imurchie** [comment]
Can you provide a bit of context for this? What is the problem it solves, etc?

**Comment by yonglid** [comment]
Hi,
Sorry I actually haven't implemented it.

I'm trying to solve my SSL Cert issue - as in automating the acceptance of
the security popup warnings I'm getting every time I try to access my
browser. I set my capability to true for accepting SSL certs but it's not
working and I'm thinking it's a system thing instead of a web thing, but
not sure how to switch it over.

**Comment by jlipps** [comment]
@imurchie this is worth revisiting. @yonglid can you rebase?

**Comment by imurchie** [comment]
This all seems to already be in. https://github.com/appium/appium-android-bootstrap/commit/69b1212fb2a533d7969d4d300fa440ce147036e8

**Pull request closed without merging**
