### PR TITLE
Fix for screen orientation for devices with natural landscape orienta…

### PR DESCRIPTION
**Pull request by irenadavidov**
Fix for screen orientation for devices with natural landscape orientation (Wide screen devices)
Fix for issue #6348

### CODE REVIEW

**Comment by artkoshelev** [comment]
👍 +1

**Comment by imurchie** [comment]
Does this return the correct orientation, then? Or just handle setting?

**Comment by irenadavidov** [comment]
Yes, it returns now the correct orientation.
It checks if the device natural orientation is landscape or portrait. If it is a landscape, it will perform the rotation in the opposite way.

**Comment by irenadavidov** [comment]
Any progress with the pull request?

**Comment by imurchie** [comment]
Sorry for the delay. We are still discussing the best way to handle breaking changes.

**Comment by umutuzgur** [comment]
Hi Guys. Any update on this pull request? We are also waiting for this fix

**Comment by jlipps** [comment]
@imurchie we should revisit this

**Comment by vania-pooh** [comment]
Any chances to get this merged?

**Comment by vania-pooh** [comment]
Anybody here?

**Comment by imurchie** [comment]
I'm fine with this getting in. I'd like a little better logging (to, for instance, note that what was sent in is being changed), but that can happen by us after merging this.

**Comment by jlipps** [comment]
I like this too, I'm just wondering if it will be a breaking change for anyone relying on the previous (buggy) way of operating.

**Comment by vania-pooh** [comment]
@jlipps: wouldn't it be sufficient to reflect this breaking change in Appium release changelog (possibly in bold)?

**Comment by jlipps** [comment]
@vania-pooh the problem is more that we try to follow semantic versioning, which means we couldn't actually release this change until appium 2.0 (or 1.7, since we sometimes fudge a little and release breaking changes at minor versions as well), and that is probably not going to happen crazy soon.

@imurchie what do you think about this? it's hard to know the kind of impact it would have. another option is to merge it to a major version bump of the bootstrap and hope we don't need to make changes to it for a while. then at least the code is merged and would be updated next time we feel it's ok to make a breaking change in appium. also if people desperately want this functionality they can build a version of appium with the updated bootstrap, rather than having to patch the bootstrap code themselves.

**Comment by imurchie** [comment]
It could also be wired behind a capability, until it becomes the default.

**Comment by jlipps** [comment]
Yeah, something like `androidNaturalOrientation`. in which case that would mean @irenadavidov would need to allow a flag to be passed into the bootstrap which determines whether the natural orientation should take precedence

**Comment by vania-pooh** [comment]
@irenadavidov are you able to include such a change with ```androidNaturalOrientation```? If not I can try to send a new PR where this is fixed.

**Comment by imurchie** [comment]
We will need to either update this PR with the fix, or merge this PR and, before publishing, merge another PR that adds the ability to have `naturalOrientation` passed in from the calling code (and also, for backward compatibility, the ability to _not_ have it passed in). This should not be too difficult a change.

**Comment by vania-pooh** [comment]
@imurchie to accelerate things. Can you give me a small snippet how to get a capability from AndroidCommand object. I don't know very well the code base. It seems like it should be something like:
```
AndroidCommand command = ...;
if (command.params().get("naturalOrientation")) {
    //Then apply fixes above
}
```
Is my statement correct?

**Comment by imurchie** [comment]
@vania-pooh Yes. Along the same lines as https://github.com/appium/appium-android-bootstrap/blob/master/bootstrap/src/io/appium/android/bootstrap/handler/Orientation.java#L47 only getting `naturalOrientation` instead, and using it accordingly.
```java
boolean naturalOrientation = false;
if (params.containsKey("naturalOrientation")) {
  // I'm not sure if it will come through as a boolean or if it needs to be converted
  orientation = (boolean) params.get("naturalOrientation");
}

// ...
```

The calling code (https://github.com/appium/appium-android-driver/blob/master/lib/commands/actions.js#L34-L37) would then be modified to something like 
```js
commands.setOrientation = async function (orientation) {
  orientation = orientation.toUpperCase();
  let params = {
    orientation,
    naturalOrientation: !!this.opts.androidNaturalOrientation,
  };
  return await this.bootstrap.sendAction("orientation", {orientation});
};
```

**Comment by vania-pooh** [comment]
New PR with Java changes: https://github.com/appium/appium-android-bootstrap/pull/42

**Comment by vania-pooh** [comment]
Javascript changes: https://github.com/appium/appium-android-driver/pull/214

**Comment by imurchie** [comment]
Closing as functionality superseded by #42.

**Pull request closed without merging**
