### PR TITLE
Add support for context in xpath find strategy

### PR DESCRIPTION
**Pull request by guysmoilov**
For find commands like this one:
{"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.TextView","context":"**5**","multiple":true}}}

### CODE REVIEW

**Comment by guysmoilov** [comment]
Server side fix for appium 1.5: https://github.com/appium/appium-android-driver/pull/111

**Comment by imurchie** [comment]
I'm fine with `AccessibilityNodeInfoGetter`. This looks great! And sorry for the delay.

**Comment by imurchie** [comment]
Published in `appium-android-bootstrap@2.6.0`.

**Comment by guysmoilov** [comment]
Thanks!

**Pull request merged**
