### PR TITLE
if bootstrap log says [debug], use log.debug rather than log.info

### PR DESCRIPTION
**Pull request by jlipps**
fixx appium/appium#8725

### CODE REVIEW

**Review by imurchie — APPROVED** [review]

**Comment by jlipps** [comment]
btw @dpgraham do you know why circle is failing with some android api level ant warning?

**Comment by imurchie** [comment]
I think I set that up, since this is the simplest Java/JS project. I didn't in the end have time to figure out how to configure.

I'll turn it off.

**Comment by imurchie** [comment]
No more CircleCI for this repo.

**Comment by dpgraham** [comment]
I registered appium-android-bootstrap to use circleci. I was evaluating it. Apparently it runs CI tests even if you don't have a YML file specified. I'll disable it.

**Comment by jlipps** [comment]
Yay! @imurchie can you merge & publish? For some reason ant isn't working on my system anymore.

**Comment by dpgraham** [comment]
Ahh yes, it was actually `a ppium-uiautomator2-driver` that Circle was set up on.

**Comment by imurchie** [comment]
Yeah, ant doesn't work for Android tools above 22. I have the tools that I swap in and out to publish. :(

**Comment by imurchie** [comment]
Published in `appium-android-bootstrap@2.9.3`.

**Pull request merged**
