### PR TITLE
Correct orientation processing for devices with natural landscape ori…

### PR DESCRIPTION
**Pull request by vania-pooh**
…entation (fixes #6348)

### CODE REVIEW

**Comment by imurchie** [comment]
So this is pulling in the changes proposed in #21?

**Review by imurchie — APPROVED** [review]
Looks good! This should not make it a breaking change anymore.

**Comment by vania-pooh** [comment]
@imurchie I copy-pasted most of the code from #21 and added fixes we discussed.

**Comment by imurchie** [comment]
https://github.com/appium/appium-android-driver/pull/214

**Comment by imurchie** [comment]
Thanks for taking this on! Published in `appium-android-bootstrap@2.8.0`.

**Pull request merged**
